#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap          14
bspc config border_radius 5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true
bspc config pointer_motion_interval 7

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
#bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Plank manage=off locked=on border=off state=floating focus=off

bspc subscribe node_add | while read -r _; do
  xdo raise -N Plank
done &

#"#6c71c4"
#"#ffa6a6"
bspc config focused_border_color        "#232a2d"
bspc config normal_border_color         "#1a1b26"
bspc config active_border_color         "#444b6a"
#ffffff
#282828

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
#bash ~/.config/polybar/launch.sh --shapes &
$HOME/.config/polybar/launch.sh
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  
# Picom
plank &

#$HOME/Documents/a.sh &

picom --config $HOME/.config/picom.conf --experimental-backends --xrender-sync-fence &
# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &


# Low battery notifier
#~/.config/bspwm/scripts/low_bat_notifier.sh &

#xss-lock -l ~/Documents/transfer-sleep-lock-generic-delay.sh &



